### PR TITLE
Enable containers to start as a non-root user

### PR DESCRIPTION
**Pull request by felipecrs**
- [ ] Build for different archs

Fixes https://github.com/just-containers/s6-overlay/issues/19, despite it's already closed.

### CODE REVIEW

**Comment by felipecrs** [comment]
I would like to hear some thoughts from the maintainers.

**Comment by felipecrs** [comment]
Ok... I just noticed that `init` is not meant to be run by `sh` (the shebang). We can solve it by wrapping it into a `sh` script, which executes it using the `execline`.

**Comment by jprjr** [comment]
Can you explain some of these changes? I'm not familiar with shc, what is that doing?

**Comment by felipecrs** [comment]
> Can you explain some of these changes? I'm not familiar with shc, what is that doing?

Sure! Basically here, we make use of the [suid bit](https://www.howtogeek.com/656646/how-to-use-suid-sgid-and-sticky-bits-on-linux/). With the suid bit set, the script run as root no matter what user has started it (this is how `su` works). However, the suid bit can't be used in Shell Scripts, only in binaries.

So, in order to convert the `init` script to a binary, we use `shc` (Shell Script Compiler), which with the `-S` option makes the needed changes in the binary in order to make it run as root.

**Comment by dreamcat4** [comment]
This is very interesting. Have we got a better way to do this? @felipecrs are you already on the s6 supervision mailinglist to ask there if this feature can be added into s6? That would probably help everybody else out who wants this feature (I do too!). To make it a little more clean and acceptable. Rather than wrapping in a script which, well I love writing scripts but since s6 is a C project this maybe should be possible to do in the C of s6? Not sure myself have not looked at the code. But I'm sure those guys on the mailinglist can help. They are really much more familiar with it. Thanks again for providing this workaround. It could potentially be very useful. Perhaps also a real world example where you are using it yourself too? Would love to see that.

**Comment by felipecrs** [comment]
> Have we got a better way to do this? 

I played with C and Go to make such a thing ([`fixuid`](https://github.com/boxboat/fixuid) also uses this approach and it's made in Go), but I found that `shc` was the cleanest approach, at least for my project [`fixdockergid`](https://github.com/felipecrs/fixdockergid). Just because I could still use the good and old shell script, which is much simpler for what I had to do.

> @felipecrs are you already on the s6 supervision mailinglist to ask there if this feature can be added into s6?

Not really (yet), so sad that they're not in GitHub. 😕

> since s6 is a C project this maybe should be possible to do in the C of s6?

Definitely, `shc` wraps the shell script into a C compiled binary after all.

> Perhaps also a real world example where you are using it yourself too? Would love to see that.

For sure, my Docker image [`jenkins-agent-dind`](https://github.com/felipecrs/jenkins-agent-dind) already uses this approach, and it works flawlessly. Feel free to give it a try:

```sh-session
$ docker run -it --rm --privileged --user "$(id -u):$(id -g)" ghcr.io/felipecrs/jenkins-agent-dind
```

It automatically fixes the UID and GID from the user in the container to match the user passed as a parameter using `fixuid`.

**Comment by jprjr** [comment]
I have two concerns with this approach.

First is the `setuid` bit on the `ENTRYPOINT` binary (`/init`).

I assume people using the `USER` directive are expecting **all** the processes to run as that particular user. If we use the `setuid` bit to change back to root on our `ENTRYPOINT` - then everything is going run as root. Isn't that kind of defeating the purpose of the `USER` directive?

If we instead figured out what tasks *have* to run as root and did a setuid on those bits, we'd be OK.

The other concern is shc with a `#!/bin/sh` script - from the man page:

`The compiled binary will still be dependent on the shell specified in the first line of the shell code (i.e. #!/bin/sh), thus shc does not create completely independent binaries.`

One of the goals for this is to not rely on *any* binaries on the base image. In theory, you can create an image from the `scratch` (empty) image and have a working system with just the s6-overlay.

If instead the script compiler was run on an execline script, we'd be OK since we know `execlineb` will be installed. Not sure how well `shc` works with `execline` scripts.

**Comment by jprjr** [comment]
I think a better approach would be:

1. Identify what parts of the init process must be root
2. Separate out those parts into separate `execline` scripts
3. Convert those `execline` scripts into C programs since they're likely to be short anyway.

**Comment by jprjr** [comment]
Hi, I'm going to reject this pull request.

Using setuid on the `/init` process sets the effective user ID to root for the entire supervision tree - meaning you're still running as root. I think that violates the spirit of the `USER` directive.

I've opened a separate PR that adds very, very early support for the `USER` directive - #305. I think realistically we'll have to identify what parts of `s6-overlay` require root permissions and find solutions over time.

**Comment by jprjr** [comment]
I'll re-open #19, though.

**Pull request closed without merging**
