### PR TITLE
feat: wait for services to be up before CMDing.

### PR DESCRIPTION
**Pull request by glerchundi**

### CODE REVIEW

**Comment by skarnet** [comment]
It's not looking too bad, except you are hardcoding a 1s timeout, and if services are heavy you'll need more than that. I'd suggest making another configuration variable for the `s6-svwait` timeout.

Also, you are making your life difficult by reading one environment file at a time. Just s6-envdir the env directory and multisubstitute import all the variables you need at the start of the script and be done with it. Efficiency is a thing, but reducing the number of lines of code you need is also a thing.

All in all, this pseudo-dependency management is showing its age - it works, but adding feature after feature makes it look more and more like the sysv-rc scripting nightmares that we wanted to avoid in the first place. @glerchundi, how about having a brainstorming session one of these days to see whether we can simplify the whole thing by adding s6-rc - or, alternatively, if having a second overlay with s6-rc for complex cases would be viable ?

**Comment by glerchundi** [comment]
hi @skarnet,

> Also, you are making your life difficult by reading one environment file at a time. Just s6-envdir the env directory and multisubstitute import all the variables you need at the start of the script and be done with it. Efficiency is a thing, but reducing the number of lines of code you need is also a thing.

Yep, i'll modify it whenever I get a free slot.

> All in all, this pseudo-dependency management is showing its age - it works, but adding feature after feature makes it look more and more like the sysv-rc scripting nightmares that we wanted to avoid in the first place.

Yes! I feel like everything got messed just because I didn't have time to discuss which would be the best way to add those features.

> @glerchundi, how about having a brainstorming session one of these days to see whether we can simplify the whole thing by adding s6-rc - or, alternatively, if having a second overlay with s6-rc for complex cases would be viable ?

Of course it's viable. When I opened the proposal I though to create a branch and start doing some work there but my spare time right now is too short to do that kind of work...
I think I could get a chance to do a session (hangout or whatever) in two weeks? WDYT?

**Comment by skarnet** [comment]
In two weeks sounds good. No rush, I was just mentioning that because I'm wary of the increasing complexity with dependencies. If complex dependency management is needed, I believe s6-rc is the right tool (now that it exists!) and would like to alleviate your script maintenance burden. :-)

**Comment by glerchundi** [comment]
dup #160

**Pull request closed without merging**
